import { GoogleOAuthProvider } from '@react-oauth/google';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GOOGLE_CLIENT_ID } from '@/config/auth';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId={GOOGLE_CLIENT_ID}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
